## Extra NumPy Exercise

In [1]:
import numpy as np

In [2]:
a1 = np.random.randint(10, size=6)
a1

array([5, 9, 3, 4, 6, 5])

In [3]:
a2 = np.random.randint(10, size=(3, 4))
a2

array([[5, 8, 7, 9],
       [0, 7, 4, 8],
       [8, 7, 1, 6]])

In [4]:
a3 = np.random.randint(10, size=(3, 4, 5))
a3

array([[[6, 5, 9, 5, 1],
        [9, 3, 6, 6, 5],
        [2, 8, 2, 3, 0],
        [9, 6, 5, 5, 4]],

       [[6, 6, 8, 6, 1],
        [5, 7, 8, 2, 4],
        [0, 6, 1, 5, 8],
        [5, 9, 6, 1, 8]],

       [[8, 0, 0, 2, 7],
        [2, 7, 7, 7, 6],
        [0, 0, 2, 5, 3],
        [1, 4, 9, 5, 9]]])

### NumPy Array Attributes 

In [9]:
print(f"ndim: {a1.ndim}, shape: {a1.shape}, size: {a1.size}, dtype: {a1.dtype}, itemsize: {a1.itemsize} bytes, nbytes: {a1.nbytes} bytes")

ndim: 1, shape: (6,), size: 6, dtype: int32, itemsize: 4 bytes, nbytes: 24 bytes


`nbytes` is equal to `size` times `itemsize`

In [6]:
a2.ndim, a2.shape, a2.size, a2.dtype, a2.itemsize, a2.nbytes

(2, (3, 4), 12, dtype('int32'), 4, 48)

In [7]:
a3.ndim, a3.shape, a3.size, a3.dtype, a3.itemsize, a3.nbytes

(3, (3, 4, 5), 60, dtype('int32'), 4, 240)

### Array Indexing 

In [10]:
a1

array([5, 9, 3, 4, 6, 5])

In [11]:
a1[0]

5

In [105]:
a1[-2] # use negative (-) to index from the end of an array

6

In [106]:
# how to reverse an array
a1[::-1]

array([5, 6, 4, 3, 9, 5])

In a 2-dimensional array:
array[n-th row, n-th column]

In [12]:
a2

array([[5, 8, 7, 9],
       [0, 7, 4, 8],
       [8, 7, 1, 6]])

In [14]:
a2[0] # takes the first row

array([5, 8, 7, 9])

In [86]:
a2[0, 1] # takes the value from the 1st row and 2nd column

8

In [43]:
# slicing technique [start:stop:step]
a2[:1]

array([[5, 8, 7, 9]])

In [47]:
# takes the value from the 1st row (0th index), 3rd column (2nd index)
a2[0, 2]

7

In [73]:
# takes each value in the 1st row (0th index) and 1st column (0th index) in the array by using slicing
# a2[:3, :1]
# a2[:a2.ndim + 1, :1]
a2[:a2.shape[0], :1]

array([[5],
       [0],
       [8]])

In [108]:
a2

array([[5, 8, 7, 9],
       [0, 7, 4, 8],
       [8, 7, 1, 6]])

In [122]:
a2[::, ::-1] # reverses a 2-dimensional array

array([[9, 7, 8, 5],
       [8, 4, 7, 0],
       [6, 1, 7, 8]])

In [75]:
a3

array([[[6, 5, 9, 5, 1],
        [9, 3, 6, 6, 5],
        [2, 8, 2, 3, 0],
        [9, 6, 5, 5, 4]],

       [[6, 6, 8, 6, 1],
        [5, 7, 8, 2, 4],
        [0, 6, 1, 5, 8],
        [5, 9, 6, 1, 8]],

       [[8, 0, 0, 2, 7],
        [2, 7, 7, 7, 6],
        [0, 0, 2, 5, 3],
        [1, 4, 9, 5, 9]]])

In a 3-dimensional array: array[n-th matrix, n-th row, n-th column]

In [85]:
a3[0, 0, 4]

1

In [101]:
a3[:, :, 2:3] # get's the values from each matrices, each row, and the 3rd column

array([[[9],
        [6],
        [2],
        [5]],

       [[8],
        [8],
        [1],
        [6]],

       [[0],
        [7],
        [2],
        [9]]])

In [124]:
a3

array([[[6, 5, 9, 5, 1],
        [9, 3, 6, 6, 5],
        [2, 8, 2, 3, 0],
        [9, 6, 5, 5, 4]],

       [[6, 6, 8, 6, 1],
        [5, 7, 8, 2, 4],
        [0, 6, 1, 5, 8],
        [5, 9, 6, 1, 8]],

       [[8, 0, 0, 2, 7],
        [2, 7, 7, 7, 6],
        [0, 0, 2, 5, 3],
        [1, 4, 9, 5, 9]]])

In [123]:
a3[::, ::, ::-1] # reverses a 3-dimensional array

array([[[1, 5, 9, 5, 6],
        [5, 6, 6, 3, 9],
        [0, 3, 2, 8, 2],
        [4, 5, 5, 6, 9]],

       [[1, 6, 8, 6, 6],
        [4, 2, 8, 7, 5],
        [8, 5, 1, 6, 0],
        [8, 1, 6, 9, 5]],

       [[7, 2, 0, 0, 8],
        [6, 7, 7, 7, 2],
        [3, 5, 2, 0, 0],
        [9, 5, 9, 4, 1]]])

### Creating copies of an array with .copy()

In [125]:
a1_copy = a1.copy()

In [126]:
a1_copy

array([5, 9, 3, 4, 6, 5])

In [128]:
a1_copy[0] = 99
a1[0], a1_copy[0]

(5, 99)

### Array Concatenation

In [133]:
x = np.random.randint(10, size=5)
y = np.random.randint(10, size=5)
x, y

(array([1, 2, 7, 8, 4]), array([0, 1, 6, 6, 8]))

In [144]:
# np.concatenate([x, y]) # stack two (or more) arrays
np.concatenate([x, y], axis=0) # stack two (or more) arrays

array([1, 2, 7, 8, 4, 0, 1, 6, 6, 8])

In [139]:
np.vstack([x, y]) # stack the arrays vertically

array([[1, 2, 7, 8, 4],
       [0, 1, 6, 6, 8]])

In [138]:
np.hstack([x, y]) # stack the arrays horizontally

array([1, 2, 7, 8, 4, 0, 1, 6, 6, 8])

In [145]:
np.dstack([x, y])

array([[[1, 0],
        [2, 1],
        [7, 6],
        [8, 6],
        [4, 8]]])

### Array Splitting

In [168]:
z = np.random.randint(10, size=10)
z1, z2 = np.split(z, [5])
print(z, z1, z2)

[5 9 1 0 9 1 0 4 6 7] [5 9 1 0 9] [1 0 4 6 7]


In [175]:
z3 = np.random.randint(10, size=(3, 3))
z3

array([[2, 9, 3],
       [9, 6, 1],
       [5, 8, 7]])

In [184]:
np.vsplit(z3, [1, 2]) # split an array vertically

[array([[2, 9, 3]]), array([[9, 6, 1]]), array([[5, 8, 7]])]

In [185]:
np.hsplit(z3, [1, 2]) # split an array horizontally

[array([[2],
        [9],
        [5]]),
 array([[9],
        [6],
        [8]]),
 array([[3],
        [1],
        [7]])]