## Extra NumPy Exercise

In [1]:
import numpy as np

In [2]:
a1 = np.random.randint(10, size=6)
a1

array([7, 9, 7, 0, 5, 0])

In [3]:
a2 = np.random.randint(10, size=(3, 4))
a2

array([[5, 7, 2, 5],
       [2, 4, 9, 6],
       [4, 7, 8, 8]])

In [4]:
a3 = np.random.randint(10, size=(3, 4, 5))
a3

array([[[2, 9, 8, 6, 0],
        [5, 9, 4, 0, 2],
        [8, 4, 0, 1, 9],
        [2, 6, 4, 3, 3]],

       [[8, 3, 4, 5, 2],
        [1, 7, 7, 8, 6],
        [1, 7, 7, 5, 2],
        [5, 8, 6, 7, 3]],

       [[0, 9, 3, 9, 0],
        [2, 9, 8, 9, 3],
        [9, 6, 4, 3, 9],
        [1, 7, 5, 7, 6]]])

### NumPy Array Attributes 

In [5]:
print(f"ndim: {a1.ndim}, shape: {a1.shape}, size: {a1.size}, dtype: {a1.dtype}, itemsize: {a1.itemsize} bytes, nbytes: {a1.nbytes} bytes")

ndim: 1, shape: (6,), size: 6, dtype: int32, itemsize: 4 bytes, nbytes: 24 bytes


`nbytes` is equal to `size` times `itemsize`

In [6]:
a2.ndim, a2.shape, a2.size, a2.dtype, a2.itemsize, a2.nbytes

(2, (3, 4), 12, dtype('int32'), 4, 48)

In [7]:
a3.ndim, a3.shape, a3.size, a3.dtype, a3.itemsize, a3.nbytes

(3, (3, 4, 5), 60, dtype('int32'), 4, 240)

### Array Indexing 

In [8]:
a1

array([7, 9, 7, 0, 5, 0])

In [9]:
a1[0]

7

In [10]:
a1[-2] # use negative (-) to index from the end of an array

5

In [11]:
# how to reverse an array
a1[::-1]

array([0, 5, 0, 7, 9, 7])

In a 2-dimensional array:
array[n-th row, n-th column]

In [12]:
a2

array([[5, 7, 2, 5],
       [2, 4, 9, 6],
       [4, 7, 8, 8]])

In [13]:
a2[0] # takes the first row

array([5, 7, 2, 5])

In [14]:
a2[0, 1] # takes the value from the 1st row and 2nd column

7

In [15]:
# slicing technique [start:stop:step]
a2[:1]

array([[5, 7, 2, 5]])

In [16]:
# takes the value from the 1st row (0th index), 3rd column (2nd index)
a2[0, 2]

2

In [17]:
# takes each value in the 1st row (0th index) and 1st column (0th index) in the array by using slicing
# a2[:3, :1]
# a2[:a2.ndim + 1, :1]
a2[:a2.shape[0], :1]

array([[5],
       [2],
       [4]])

In [18]:
a2

array([[5, 7, 2, 5],
       [2, 4, 9, 6],
       [4, 7, 8, 8]])

In [19]:
a2[::, ::-1] # reverses a 2-dimensional array

array([[5, 2, 7, 5],
       [6, 9, 4, 2],
       [8, 8, 7, 4]])

In [20]:
a3

array([[[2, 9, 8, 6, 0],
        [5, 9, 4, 0, 2],
        [8, 4, 0, 1, 9],
        [2, 6, 4, 3, 3]],

       [[8, 3, 4, 5, 2],
        [1, 7, 7, 8, 6],
        [1, 7, 7, 5, 2],
        [5, 8, 6, 7, 3]],

       [[0, 9, 3, 9, 0],
        [2, 9, 8, 9, 3],
        [9, 6, 4, 3, 9],
        [1, 7, 5, 7, 6]]])

In a 3-dimensional array: array[n-th matrix, n-th row, n-th column]

In [21]:
a3[0, 0, 4]

0

In [22]:
a3[:, :, 2:3] # get's the values from each matrices, each row, and the 3rd column

array([[[8],
        [4],
        [0],
        [4]],

       [[4],
        [7],
        [7],
        [6]],

       [[3],
        [8],
        [4],
        [5]]])

In [23]:
a3

array([[[2, 9, 8, 6, 0],
        [5, 9, 4, 0, 2],
        [8, 4, 0, 1, 9],
        [2, 6, 4, 3, 3]],

       [[8, 3, 4, 5, 2],
        [1, 7, 7, 8, 6],
        [1, 7, 7, 5, 2],
        [5, 8, 6, 7, 3]],

       [[0, 9, 3, 9, 0],
        [2, 9, 8, 9, 3],
        [9, 6, 4, 3, 9],
        [1, 7, 5, 7, 6]]])

In [24]:
a3[::, ::, ::-1] # reverses a 3-dimensional array

array([[[0, 6, 8, 9, 2],
        [2, 0, 4, 9, 5],
        [9, 1, 0, 4, 8],
        [3, 3, 4, 6, 2]],

       [[2, 5, 4, 3, 8],
        [6, 8, 7, 7, 1],
        [2, 5, 7, 7, 1],
        [3, 7, 6, 8, 5]],

       [[0, 9, 3, 9, 0],
        [3, 9, 8, 9, 2],
        [9, 3, 4, 6, 9],
        [6, 7, 5, 7, 1]]])

### Creating copies of an array with .copy()

In [25]:
a1_copy = a1.copy()

In [26]:
a1_copy

array([7, 9, 7, 0, 5, 0])

In [27]:
a1_copy[0] = 99
a1[0], a1_copy[0]

(7, 99)

### Array Concatenation

In [28]:
x = np.random.randint(10, size=5)
y = np.random.randint(10, size=5)
x, y

(array([2, 5, 1, 8, 8]), array([5, 0, 3, 9, 4]))

In [29]:
# np.concatenate([x, y]) # stack two (or more) arrays
np.concatenate([x, y], axis=0) # stack two (or more) arrays

array([2, 5, 1, 8, 8, 5, 0, 3, 9, 4])

In [30]:
np.vstack([x, y]) # stack the arrays vertically

array([[2, 5, 1, 8, 8],
       [5, 0, 3, 9, 4]])

In [31]:
np.hstack([x, y]) # stack the arrays horizontally

array([2, 5, 1, 8, 8, 5, 0, 3, 9, 4])

In [32]:
np.dstack([x, y])

array([[[2, 5],
        [5, 0],
        [1, 3],
        [8, 9],
        [8, 4]]])

### Array Splitting

In [33]:
z = np.random.randint(10, size=10)
z1, z2 = np.split(z, [5])
print(z, z1, z2)

[9 4 5 1 7 8 4 0 4 2] [9 4 5 1 7] [8 4 0 4 2]


In [34]:
z3 = np.random.randint(10, size=(3, 3))
z3

array([[8, 0, 5],
       [1, 0, 9],
       [0, 9, 0]])

In [35]:
np.vsplit(z3, [1, 2]) # split an array vertically

[array([[8, 0, 5]]), array([[1, 0, 9]]), array([[0, 9, 0]])]

In [36]:
np.hsplit(z3, [1, 2]) # split an array horizontally

[array([[8],
        [1],
        [0]]),
 array([[0],
        [0],
        [9]]),
 array([[5],
        [9],
        [0]])]