# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [10]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], 
          [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3], [4, 5, 6]], 
         [[7, 8, 9], [10, 11, 12]], 
         [[13, 14, 15], [16, 17, 18]]])

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [12]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [13]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [14]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 2, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [18]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [23]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10, 2))
ones, ones.shape

(array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 (10, 2))

In [24]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7, 2, 3))
zeros, zeros.shape

(array([[[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]),
 (7, 2, 3))

In [25]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [26]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0, 10, size=(7, 2))

array([[7, 5],
       [5, 5],
       [3, 6],
       [6, 7],
       [0, 8],
       [9, 8],
       [3, 7]])

In [28]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random([3, 5])

array([[0.75778831, 0.32071121, 0.02015884, 0.33038446, 0.54304489],
       [0.29952213, 0.46964354, 0.39955544, 0.77418252, 0.20439051],
       [0.83129745, 0.46224696, 0.61618518, 0.23399412, 0.4577835 ]])

In [31]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0, 10, size=(4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [37]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a4 = np.random.randint(0, 10, size=(3, 7))
print(a4)
# Find the unique numbers in the array you just created
np.unique(a4)

[[0 7 2 2 0 4 9]
 [6 9 8 6 8 7 1]
 [0 6 6 7 4 2 7]]


array([0, 1, 2, 4, 6, 7, 8, 9])

In [38]:
# Find the 0'th index of the latest array you created
a4[0]

array([0, 7, 2, 2, 0, 4, 9])

In [39]:
# Get the first 2 rows of latest array you created
a4[:2]

array([[0, 7, 2, 2, 0, 4, 9],
       [6, 9, 8, 6, 8, 7, 1]])

In [40]:
# Get the first 2 values of the first 2 rows of the latest array
a4[:2, :2]

array([[0, 7],
       [6, 9]])

In [46]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a5 = np.random.randint(0, 10, size=(3, 5))
ones = np.ones([3, 5])
a5, ones

(array([[6, 1, 2, 0, 4],
        [0, 7, 0, 0, 1],
        [1, 5, 6, 4, 0]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [47]:
# Add the two arrays together
a5 + ones

array([[7., 2., 3., 1., 5.],
       [1., 8., 1., 1., 2.],
       [2., 6., 7., 5., 1.]])

In [48]:
# Create another array of ones of shape (5, 3)
ones_1 = np.ones([5, 3])
ones_1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
# Try add the array of ones and the other most recent array together
a5 + ones_1

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [50]:
a5.shape, ones_1.shape

((3, 5), (5, 3))

The reason is because for 2 arrays

In [53]:
a5 + ones_1.T

array([[7., 2., 3., 1., 5.],
       [1., 8., 1., 1., 2.],
       [2., 6., 7., 5., 1.]])

In [55]:
a5.shape, ones_1.T.shape

((3, 5), (3, 5))

In [56]:
# Create another array of ones of shape (3, 5)
ones_2 = np.ones([3, 5])
ones_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
# Subtract the new array of ones from the other most recent array
a5 - ones_2

array([[ 5.,  0.,  1., -1.,  3.],
       [-1.,  6., -1., -1.,  0.],
       [ 0.,  4.,  5.,  3., -1.]])

In [59]:
# Multiply the ones array with the latest array
a5 * ones_2

array([[6., 1., 2., 0., 4.],
       [0., 7., 0., 0., 1.],
       [1., 5., 6., 4., 0.]])

In [60]:
# Take the latest array to the power of 2 using '**'
a5**2

array([[36,  1,  4,  0, 16],
       [ 0, 49,  0,  0,  1],
       [ 1, 25, 36, 16,  0]])

In [61]:
# Do the same thing with np.square()
np.square(a5)

array([[36,  1,  4,  0, 16],
       [ 0, 49,  0,  0,  1],
       [ 1, 25, 36, 16,  0]])

In [62]:
# Find the mean of the latest array using np.mean()
np.mean(a5)

2.466666666666667

In [63]:
# Find the maximum of the latest array using np.max()
np.max(a5)

7

In [64]:
# Find the minimum of the latest array using np.min()
np.min(a5)

0

In [65]:
# Find the standard deviation of the latest array
np.std(a5)

2.4997777679003566

In [66]:
# Find the variance of the latest array
np.var(a5)

6.248888888888888

In [67]:
# Reshape the latest array to (3, 5, 1)
np.reshape(a5, newshape=(3, 5, 1))

array([[[6],
        [1],
        [2],
        [0],
        [4]],

       [[0],
        [7],
        [0],
        [0],
        [1]],

       [[1],
        [5],
        [6],
        [4],
        [0]]])

In [69]:
# Transpose the latest array
a5, a5.T

(array([[6, 1, 2, 0, 4],
        [0, 7, 0, 0, 1],
        [1, 5, 6, 4, 0]]),
 array([[6, 0, 1],
        [1, 7, 5],
        [2, 0, 6],
        [0, 0, 4],
        [4, 1, 0]]))

What does the transpose do?

Answer: Transpose flips the shape of the array

In [72]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a6 = np.random.randint(0, 10, size=(3,3))
a7 = np.random.randint(0, 10, size=(3,2))

In [73]:
a6

array([[0, 2, 1],
       [4, 9, 5],
       [6, 3, 6]])

In [74]:
a7

array([[7, 0],
       [5, 7],
       [4, 3]])

In [75]:
# Perform a dot product on the two newest arrays you created
np.dot(a6, a7)

array([[14, 17],
       [93, 78],
       [81, 39]])

In [76]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a8 = np.random.randint(0, 10, size=(4,3))
a9 = np.random.randint(0, 10, size=(4,3))

In [77]:
a8

array([[1, 5, 5],
       [0, 8, 5],
       [2, 3, 3],
       [2, 9, 2]])

In [78]:
a9

array([[2, 3, 6],
       [3, 8, 0],
       [7, 6, 1],
       [7, 0, 8]])

In [79]:
# Perform a dot product on the two newest arrays you created
np.dot(a8, a9)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [80]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(a8, a9.T)

array([[47, 43, 42, 47],
       [54, 64, 53, 40],
       [31, 30, 35, 38],
       [43, 78, 70, 30]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [91]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a10 = np.random.randint(0, 10, size=(3,2))
a11 = np.random.randint(0, 10, size=(3,2))

In [92]:
a10

array([[3, 4],
       [6, 0],
       [2, 1]])

In [93]:
a11

array([[8, 9],
       [5, 9],
       [2, 7]])

In [94]:
# Compare the two arrays with '>'
a10 > a11

array([[False, False],
       [ True, False],
       [False, False]])

What happens when you compare the arrays with `>`?

In [95]:
# Compare the two arrays with '>='
a10 >= a11

array([[False, False],
       [ True, False],
       [ True, False]])

In [96]:
# Find which elements of the first array are greater than 7
a10 > 7

array([[False, False],
       [False, False],
       [False, False]])

In [97]:
# Which parts of each array are equal? (try using '==')
a10 == 7

array([[False, False],
       [False, False],
       [False, False]])

In [99]:
a10

array([[3, 4],
       [6, 0],
       [2, 1]])

In [98]:
# Sort one of the arrays you just created in ascending order
np.sort(a10)

array([[3, 4],
       [0, 6],
       [1, 2]])

In [100]:
# Sort the indexes of one of the arrays you just created
np.argsort(a11)

array([[0, 1],
       [0, 1],
       [0, 1]], dtype=int64)

In [104]:
np.argsort(a10)

array([[0, 1],
       [1, 0],
       [1, 0]], dtype=int64)

In [102]:
a10

array([[3, 4],
       [6, 0],
       [2, 1]])

In [111]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a10, axis=0)

array([1, 0], dtype=int64)

In [110]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a10, axis=0)

array([2, 1], dtype=int64)

In [112]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a11, axis=1)

array([1, 1, 1], dtype=int64)

In [113]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a11, axis=1)

array([0, 0, 0], dtype=int64)

In [117]:
# Create an array of normally distributed random numbers
a12 = np.random.randn(3,2)
a12

array([[-0.72817925, -1.80188797],
       [ 0.46771708, -1.55143394],
       [-0.51049322, -0.73295114]])

In [119]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a13 = np.arange(1, 100, 10)
a13

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.